### ISSUE TITLE
Hard-wired language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [trema-tech/moodle-theme_trema#1]
Hi,

I just translated your trema theme in AMOS for the mexican Spanish language pack.

But, when I try to use it as a Spanish-language user, I found  some portuguese language strings.

I think that your nice plugin would be even better if these hard-wired strings were converted into English language strings, so that they would be available for translation in AMOS.

The strings I am most worried about are:

Identificação de usuário 
Nova senha 
Clique para inserir texto
Mostrar endereço de email 
Esconder o menu ...
Permitir que todos vejam...
Apenas os participantes...
Cidade/Município 
Selecione um país 
Atualizar perfil
particle-circles

And the list for selecting a country in the Style guide shows the names of the countries in portuguese, not in the user language (nor English).
Thanks in advance

**Comment by rmady** [comment]
Hi there @germanvaleroelizondo,

We fixed this issue in commits f39c974 and 6dea959. The styleguide page it's a demo from the CSS all over the theme, so we deleted some things and keep others with strings.

Thank you so much for your contribution :+1:

**Comment by germanvaleroelizondo** [comment]
Hi,
Thanks for the changes.
When will the new version be available in the Moodle plugins database at https://moodle.org/plugins/theme_trema ?

**Comment by rmady** [comment]
Hi,
It's already there. We implemented in releases 3.6.0.1 and 3.5.0.1.
I just checked and the strings are in AMOS too.
