### ISSUE TITLE
Dashboard ALERT link should go to Security page, not Performance.

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#101]
![image](https://user-images.githubusercontent.com/3808579/152289789-e0ca853b-5c1e-4efc-be4b-86f49cec4e39.png)

Clicking on the link takes you to:

/report/performance/index.php

Link should take you to:

/report/security/index.php

**Comment by rmady** [comment]
Awesome @michael-milette 
As I said: my mistake, this link changed and I didn't notice.

**Comment by michael-milette** [comment]
Thank you @rmady
