### ISSUE TITLE
Login form: password-reset-option missing if "remember user" is deactivated in admin settings

### ISSUE THREAD

**Issue by dermuck** [trema-tech/moodle-theme_trema#106]
The default login-window contains 3 informations directly below the login-button:
- a checkbox to enables remembering of usernames via cookie MOODLEID
- the link to forgot_password.php
- an information about required cookies

Disabling the option rememberusernames in admin settings causes theme trema to remove the corresponding checkbox AND the link to the password-reset-functionality from the login window, rendering the user helpless if he forgot his password.

<img width="883" alt="issue_resetpassword" src="https://user-images.githubusercontent.com/101058595/159919863-631cdd35-6f77-435f-a6f1-652ae0d46504.png">

**Comment by michael-milette** [comment]
Hi @dermuck ,

I agree that having the option to enable/disable remembering the username is good.

I also think that it is good to have an option to control the visibility of the forgot password link is very useful too.

I agree that both options should NOT be controlled by the same Moodle setting. I have worked with many organizations who don't want the user browser to remember the username but they DO want the link to change the password.

What would be even better would be to create a Trema setting that would allow the administrator to customize the forgot username or password link. If this new text field is empty, the link would be removed from the login page.

This solution would also enable administrators the option of changing the URL completely. 

Use case A: Some organizations might prefer to have a link to a helpdesk form where a user could request help to login.

Use case B: Some organization, who use OAuth2 or other authentication method, might also have their own custom URL for resetting a password.

Best regards,

Michael Milette

**Comment by dermuck** [comment]
Hi @michael-milette ,
the moodle setting rememberusername is indeed a very useful option, and it prevents the system from setting another cookie.
Also the use cases for setting a custom password reset URL are quite likely to occur in many moodle installations out there. But I do not agree with You that there should be a setting to control the password reset URL within theme Trema. 

There may be moodle installations that offer more than one theme, and recovering your password should not be theme-dependent. For the uses cases You described above, there already exists a moodle-option to set a custom URL. Its named forgottenpasswordurl, You can find it in the auth plugins overview (/admin/settings.php?section=manageauths). Any new Trema-specific setting might collide with this existing setting.
Therefore I personally would prefer fixing the display bug in Trema and not messing around with system-wide settings within a theme. 

Best regards,
Markus

**Comment by rarnott001** [comment]
Hi. Any chance of telling me where to find this setting. new trema installed in moodle 4.x and the forgotten username and password option has disappeared from login screen

**Comment by michael-milette** [comment]
So nice to have this fixed in the latest release here on GitHub. Thank you @rmady !

Best regards,

Michael
