### ISSUE TITLE
Feature request: Option to select no background on login page

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#109]
At the moment, your two choices are particles or image. It would be nice to also have an option to select no background image instead of expecting the user to create and upload a blank or transparent image on for the login page.

**Comment by michael-milette** [comment]
Hi @rmady ,

This new feature did not make it into the version 4.0 of Trema. Could you please add it in?

Best regards,

Michael

**Comment by rmady** [comment]
Great new option on login page. 
Thank you Michael lol

Kind regards,
Rodrigo Mady
