### ISSUE TITLE
Front page title off centre

### ISSUE THREAD

**Issue by sloanie1981** [trema-tech/moodle-theme_trema#11]
Hi the area for inputting the front page title is slightly off-centre. I've tried putting a couple of spaces in there to centralise it but it's not working.

Could you help please?

Also of you could add in a section for social media buttons, that would be awesome.

**Comment by rmady** [comment]
Hi there,

First, sorry for the delay. 
What is front page title? Please, can you send some screenshot to explain better. 
I tryed to figure out this off-centre and got no success. Below we got the screenshot from https://trema.tech/ and the front page title is ok.

![Captura de tela de 2019-04-10 15-37-25](https://user-images.githubusercontent.com/8494871/55907164-5af4b580-5bac-11e9-94d7-07dac86fe094.png)

And you can add a section with social media buttons in settings "theme_trema | defaultfrontpagebody", we add some info in theme trema site too, you can see in the image below. Another option is to put in "theme_trema | defaultfooter" that we are using too.
![Captura de tela de 2019-04-10 15-37-53](https://user-images.githubusercontent.com/8494871/55907807-241f9f00-5bae-11e9-90f3-6d967c3d142e.png)

Do you have another suggestion for social media buttons? Please, can you send some pics or explain better?

Thanks for your contribution!

**Comment by sloanie1981** [comment]
Hi Rodrigo,

Thanks for getting back to me. Please see the attached screenshot for your reference.

I've put down a screenshot of the eguru theme social media settings. It's made easier for folk like me who don't have a great knowledge of coding. They also added in sections like that so you can easily put down the contact details which includes the contact us hyperlink.

The site is www.elevationhealth.co.uk and the site I also use is www.divedoctor.co.uk which I'm using the eguru theme. I love the slick stylish style of your theme though as it suits the style that I'm going for with elevation.

Thanks for looking at this for me.

Stuart



[Image]




[Image]


[Image]

**Comment by rmady** [comment]
Hi there,

Your screenshots are broken :/
But I can see the bug in your site. We fixed the front page title off centre issue in commit fe9d1cfe732785e23b47784cb710f2ae8e674965.
Please, can you test this issue?

And you can make your social media icons just like in Eguru but you should copy the HTML structure and replace as you want it. We know that is easier to do something like Eguru but we limit the options doing something like that so we prefer to make footer fully customizeble.

Please, update your theme trema with our new release to fix.
We really appreciate your contribution and like your site with trema.

**Comment by sloanie1981** [comment]
Hey Rodrigo,

That's fixed it thank you. I'll have a look at the buttons html and see if I can get it to work.

I've added a "contact us" section on the footer which looks great on the computer but looks too wide on the mobile. What would I need to do to get the size to adjust automatically for the mobile screen size? See the coding I've used below...

<form
action"../../local/contact/index.php" method="post" class="contact-us">
    <fieldset>
        <label for="name" id="namelabel">Your name <strong class="required">(required)</strong></label><br>
        <input id="name" name="name" type="text" size="57" maxlength="45" pattern="[A-zÀ-ž]([A-zÀ-ž\s]){2,}"
                title="Minimum 3 letters/spaces." required="required" value=""><br>
        <label for="email" id="emaillabel">Email address <strong class="required">(required)</strong></label><br>
        <input id="email" name="email" type="email" size="57" maxlength="60" required="required" value=""><br>
        <label for="subject" id="subjectlabel">Subject <strong class="required">(required)</strong></label><br>
        <input id="subject" name="subject" type="text" size="57" maxlength="80" minlength="5"
                title="Minimum 5 characters." required="required"><br>
        <label for="message" id="messagelabel">Message <strong class="required">(required)</strong></label><br>
        <textarea id="message" name="message" rows="5" cols="58" minlength="5"
                title="Minimum 5 characters." required="required"></textarea><br>
        <input type="hidden" id="sesskey" name="sesskey" value="">
        <script>document.getElementById('sesskey').value = M.cfg.sesskey;</script>
    </fieldset>
    <div>
        <input type="submit" name="submit" id="submit" value="Send">
    </div>
</form>

I've tried to add margins in there but perhaps in the wrong place.

Any assistance would be much appreciated.

Cheers

Stuart
________________________________

**Comment by rmady** [comment]
Hi Stuart,

As Trema is licensed under the GNU GPLv3 License it comes with NO support but I will help you this time and maybe you can help me with chocolates sometime hahah
You should study this: https://getbootstrap.com/docs/4.0/components/forms/
Access this to add the social media icons: https://fontawesome.com/v4.7.0/
And finally I would suggest to add this code in trema config: `theme_trema | defaultfooter` 

And try this code below. I just add some bootstrap classes as you can see.
```
<div class="row">
	<div class="col-md-8">
		<form action"..="" ..="" local="" contact="" index.php"="" method="post" class="contact-us form">
			<fieldset>
				<label class="col-form-label" for="name" id="namelabel">Your name <strong class="required">(required)</strong></label><br>
				<input class="form-control" id="name" name="name" type="text" size="57" maxlength="45" pattern="[A-zÀ-ž]([A-zÀ-ž\s]){2,}" title="Minimum 3 letters/spaces." required="required" value=""><br>
				<label class="col-form-label" for="email" id="emaillabel">Email address <strong class="required">(required)</strong></label><br>
				<input class="form-control" id="email" name="email" type="email" size="57" maxlength="60" required="required" value=""><br>
				<label class="col-form-label" for="subject" id="subjectlabel">Subject <strong class="required">(required)</strong></label><br>
				<input class="form-control" id="subject" name="subject" type="text" size="57" maxlength="80" minlength="5" title="Minimum 5 characters." required="required"><br>
				<label class="col-form-label" for="message" id="messagelabel">Message <strong class="required">(required)</strong></label><br>
				<textarea id="message" name="message" rows="5" cols="58" minlength="5" title="Minimum 5 characters." required="required"></textarea><br>
				<input class="form-control" type="hidden" id="sesskey" name="sesskey" value="">
				<script>document.getElementById('sesskey').value = M.cfg.sesskey;</script>
			</fieldset>
			<div>
				<input class="btn btn-primary" type="submit" name="submit" id="submit" value="Send">
			</div>
		</form>
	</div>

	<div class="col-md-4">
		<h3>Contact Us</h3>

		<ul class="labeled-icons">
			<li><span class="fa fa-globe fa-2x"></span><a href="https://trema.tech/" target="_blank" style="cursor: pointer;"><p>https://trema.tech/</p></a></li>
			<li><span class="fa fa-github fa-2x"></span><a href="https://github.com/trema-tech/" target="_blank" style="cursor: pointer;"><p>https://github.com/trema-tech/</p></a></li>
		</ul>
	</div>
</div>
```
