### ISSUE TITLE
theme_treme | defaultfrontpagebody, hidden

### ISSUE THREAD

**Issue by armandogomisveas** [trema-tech/moodle-theme_trema#117]
Hello.
I have upgraded to version 4 of moodle and "Cover Body" has disappeared on the web. I fill it in the backend, but it doesn't appear in the frontend.
![Captura de pantalla 2022-06-21 133721](https://user-images.githubusercontent.com/107927485/174790765-3d69f107-75ba-42bd-88fc-1334482bc43f.png)

In the previous version it worked, but not in this one. What can be?

My website is https://civipolenglish.com/

THANK YOU!

**Comment by rmady** [comment]
Hi there, 
Thank you for your help.
I fix this issue in the last release. Please, update your theme and check if everything is working as planned now.

Kind regards,
Rodrigo Mady
