### ISSUE TITLE
Missing fixes in Trema for Moodle 4.0

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#120]
Hi @rmady ,

Could you please check the following tickets? The integration of the pull requests for the following fixes and enhancements seem to have been forgotten as they are missing in the v4.0 of Trema (master branch):

- https://github.com/trema-tech/moodle-theme_trema/pull/98
- https://github.com/trema-tech/moodle-theme_trema/pull/102
- https://github.com/trema-tech/moodle-theme_trema/pull/104
- https://github.com/trema-tech/moodle-theme_trema/pull/107
- https://github.com/trema-tech/moodle-theme_trema/pull/109
- https://github.com/trema-tech/moodle-theme_trema/pull/111
- https://github.com/trema-tech/moodle-theme_trema/pull/114

When do you think you might have time to integrate these?

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @rmady ,

I updated all the patches so that they are now compatible with Trema for Moodle 4.0. There should not be any further conflicts as long as you apply them in the following order:

Please apply the fixes in the following order:

- #128 (for issue fix-86)
- #129 (for issue fix-91)
- #127 (for issue fix-101)
- #130 (for issue fix-103)
- #132 (for issue fix-105)
- #131 (for issue fix-109)
- #133 (for issue fix-113)

While you are at it, please don't forget to also apply:

- #123
- #126 

Let me know if you have any questions or concerns.

Best regards,

Michael Milette

**Comment by rmady** [comment]
Hello Michael,
Thank you for your support!
I think we make it!
