### ISSUE TITLE
defaultfrontpagebody should not be included when empty

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#122]
The defaultfrontpagebody DIV has height even when it is empty. This pushes down the content leaving an unexpected cap in the page.

![image](https://user-images.githubusercontent.com/3808579/185234551-ca90afe4-c728-43cc-a6a1-b0579094de24.png)

The HTML for defaultfrontpagebody should not be displayed in it contains no content.

**Comment by rmady** [comment]
Great fix.
Thanks a lot, Michael.

Kind regards,
Rodrigo Mady
