### ISSUE TITLE
Description should appear on course description page instead of just a card

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#124]
When you click on the name of a course in one of the course cards on the Home page to go to the course, if you are not already enrolled in the course, you should see the course image and description. Instead, you see the course card again.

![image](https://user-images.githubusercontent.com/3808579/185239979-e628be6f-cf0b-4b38-81ca-56d205441d36.png)

I feel that it would be more helpful to see the course image and description on this page. Can this be changed or at least made an option?

**Comment by michael-milette** [comment]
I submitted a pull request which adds a new setting: **Site Administration > Appearance (tab) > Theme > Trema > Content (tab) > Course Enrolment Page Format**.

When the **Course Enrolment Page Format** is set to card (the default, as it was before the patch):
![image](https://user-images.githubusercontent.com/3808579/186556942-1ac6bba8-6b70-4b09-b41d-591b15a86d6e.png)

The result is:
![image](https://user-images.githubusercontent.com/3808579/186556995-e469dea4-4d4b-49da-be54-bcc576958a00.png)

When you switch the new **Course Enrolment Page Format** setting to **Full Page**:
![image](https://user-images.githubusercontent.com/3808579/186557105-6c905b79-5c20-438e-965a-f377d5d518dc.png)

The resulting page look like this:
![image](https://user-images.githubusercontent.com/3808579/186557343-5f4b224b-6897-4162-8e16-b8d436a0ae8e.png)

Thank you for considering including this new feature. Let me know if you have any questions or concerns.

Best regards,

Michael Milette

**Comment by rmady** [comment]
Great feature Michael
Thanks a lot!

Kind regards,
Rodrigo Mady
