### ISSUE TITLE
Option to remove shading from front page banner

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#125]
Could you please add an option to enable or disable the shading on the front page banner? 

![image](https://user-images.githubusercontent.com/3808579/185243301-51742db5-3173-49ad-953e-d717ee5209cf.png)

Sometimes it is desirable to have a light colour banner with dark letters. 

![image](https://user-images.githubusercontent.com/3808579/185243361-a63f9b18-bd5a-41c0-a085-b1e9c6431373.png)

This is not currently possible due to the way the shading on the banner is generated by the PHP code.

**Comment by rmady** [comment]
Awesome Michael,
I love this new feature!

Kind regards,
Rodrigo Mady
