### ISSUE TITLE
Forum bug

### ISSUE THREAD

**Issue by bartek1044** [trema-tech/moodle-theme_trema#13]
Hello,
on forum after run this theme user's don't see options to edit, delete and replay to post because the buttons are not visible (they are there but and you can click on it but it is not visible)

**Comment by paulteach** [comment]
I investigated a bit and saw that the links are there, but the color is white, just like the background.
![Screen Shot 2019-07-13 at 16 13 05](https://user-images.githubusercontent.com/19873529/61175639-74c9de00-a589-11e9-83c0-a8c8821a3390.png)
![Screen Shot 2019-07-13 at 16 12 53](https://user-images.githubusercontent.com/19873529/61175645-7abfbf00-a589-11e9-9258-dd7bb2cbd03c.png)

**Comment by paulteach** [comment]
The "welcome"lik is blue though.
How can we fix this? Additional css? I suck at css, so if anyone can help...

**Comment by rmady** [comment]
Hi guys, we just fix this issue.
We are finishing some others issues and hope release a new version in the next week.

Thanks a lot @bartek1044 @paulteach lol
