### ISSUE TITLE
Style Guide password field is of incorrect type

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#134]
In the Trema settings > Style Guide tab, the password field is of type "text". 
![image](https://user-images.githubusercontent.com/3808579/186086213-782ca2f9-3281-4c64-bcea-f46713af0f73.png)
It should be of type "password".

**Comment by rmady** [comment]
Thank you for this update in style guide.

Kind regards,
Rodrigo Mady
