### ISSUE TITLE
Title and description in mobile view is out of header/background picture

### ISSUE THREAD

**Issue by Marcel12342** [trema-tech/moodle-theme_trema#15]
Hi all, really appreciate the design and functionalities of this theme. But after installation and try to open it with an Smartphone (iPhone Xs, iOS 12) i have the title and description out of the background picture.

Anyone an idea how to fix this?

Thanks and regards!
Marcel

![screenshot_1](https://user-images.githubusercontent.com/55705354/65438588-02496a00-de26-11e9-9e60-e98aa9d54dd6.jpeg)

**Comment by felixcancelado** [comment]
Hi trevorfurtado, thanks for being in contact supporting. I have changed the files but the issue about the header keeps on. Could you tell me what else I should do to see the titlke of the header on mobliles again? Thanks

**Comment by felixcancelado** [comment]
> Hi all, really appreciate the design and functionalities of this theme. But after installation and try to open it with an Smartphone (iPhone Xs, iOS 12) i have the title and description out of the background picture.
> 
> Anyone an idea how to fix this?
> 
> Thanks and regards!
> Marcel
> 
> ![screenshot_1](https://user-images.githubusercontent.com/55705354/65438588-02496a00-de26-11e9-9e60-e98aa9d54dd6.jpeg)

Hi Marcel, how are you doing. May you help me with that issue. I ve the same erros. What have you done to solv it? thanks in advance!

**Comment by HeyMeco** [comment]
Same problem for me too

**Comment by techAdventurer** [comment]
As a quick fix, you can add the following to the `RAW SCSS` field in the theme settings:

```css
body#page-site-index #frontpage-banner #frontpage-banner-content {
	position: absolute;
}
```
