### ISSUE TITLE
Top navigation/navbar is not aligned correctly - too high (SOLUTION INCLUDED)

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#150]
The top primary navigation/navbar/custom menu is out of alignment with the rest of the header. It is too high:

![image](https://user-images.githubusercontent.com/3808579/189233276-9d5bd21b-e055-4e47-b50c-105774ac18ba.png)

When I tried to adjust it with CSS, I ran into problems with the "more" menu. See #149 .

Using:
- Moodle 4.0.3
- Trema 4.0.0.2

Let me know if you have any questions.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @rmady ,

Please test and merge PR #179 . Thanks!

Best regards,

Michael Milette

**Comment by rmady** [comment]
Thank you very much @michael-milette lol
You are the best.

Kind regards,
Rodrigo Mady
