### ISSUE TITLE
Front Page Carrousel/Slider broken

### ISSUE THREAD

**Issue by ahsantejani** [trema-tech/moodle-theme_trema#155]
Hello,

I observed after updating the current version of theme, the front sliders are not working. they are not moving automatically nor button on side and down working for movement.

Please guide and help in this regard.

**Comment by michael-milette** [comment]
Hi @ahsantejani ,

Sorry about that. The issue has been fixed in pull request #156. If you cannot want for the next release of Trema, feel free to implement the changes yourself. Hopefully @rmady will be able to integrate soon.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @ahsantejani , 

The fix for the carrous has been integrated into the latest version of Trema here on Github. Could you please try it out and let us know if it works for you?

Best regards,

Michael

**Comment by ahsantejani** [comment]
Thank you very much. Its working perfectly now. Thanks alot.

**Comment by christopherm00** [comment]
Thanks for this update - I can confirm that it works but now the Enable Dark Overlay does not have any effect on the slider - it only works when 1 image is selected

**Comment by PTSdeveloper007** [comment]
> Thanks for this update - I can confirm that it works but now the Enable Dark Overlay does not have any effect on the slider - it only works when 1 image is selected

This is still the case with the latest Trema update and moodle 4.4. Any fixes please

**Comment by rmady** [comment]
Hello @PTSdeveloper007 @christopherm00 ,
I just created a new version with these fixes.
Please, check it out and let me know if everything is ok now.

Kind regards,
Rodrigo Mady

**Comment by ahsantejani** [comment]
Hello

I m using Moodle 4.4.3 (Build: 20240902), Trema verison 4.5.0.3 (2024111400)

Front page banner is set as 80%, now agian my banner not moving automatically. Can you please help.
