### ISSUE TITLE
Button hover color

### ISSUE THREAD

**Issue by snack753** [trema-tech/moodle-theme_trema#158]
How can I set the button hover color? Cannot find it in the Settings of the trema theme.
currently trying to work around this using the raw scss option and suggest to offer this as a feature in future versions.

**Comment by michael-milette** [comment]
There is no option to choose the button colour or button hover colour. However, there is a bug which causes the background and foreground colours to have insufficient contrast (like medium red on darker red).

**Comment by michael-milette** [comment]
This issue has been resolved in the next major release of Trema. See the "dev" branch if you want to try it out.

Best regards,

Michael Milette
