### ISSUE TITLE
ATTO editor in HTML mode does not work

### ISSUE THREAD

**Issue by sestrauss** [trema-tech/moodle-theme_trema#16]
Hello,

I find that the ATTO does not work in HTML mode when I have the Trema theme selected. Watch this [screencast showing me editing a label first in Boost, and then trying to edit it when in Trema](https://hc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6c25a923-6f60-490f-98a1-aad4013f1d01). 

Let concerning, but also visible in the screen cast and annoying, the "add a block" button gets in the way of the edit page. and a number of other pages too. 

Thanks.

**Comment by rmady** [comment]
Hi there @sestrauss,

Sorry, we fixed this issue and forget to tell you.

**Comment by sestrauss** [comment]
Thanks! What release? I am still having this issue.

**Comment by rmady** [comment]
We just did it!

**Comment by sestrauss** [comment]
Thanks. Just tried it out quickly and it looks good!
