### ISSUE TITLE
Updated version of theme for Moodle 4.1

### ISSUE THREAD

**Issue by vinee2312** [trema-tech/moodle-theme_trema#160]
When can we expect an updated version of the theme to be released for Moodle 4.1

**Comment by aelic2** [comment]
I like your template Trema !
I hope you will propose a version for Moodle 4.1
Gilles

**Comment by michael-milette** [comment]
A version of Trema for Moodle 4.1 and 4.2 are available on Moodle.org. Closing this ticket as Done.
