### ISSUE TITLE
Spanish characters aren't displaying correctly. 

### ISSUE THREAD

**Issue by malaka13** [trema-tech/moodle-theme_trema#162]
The latest theme version cannot display some Spanish characters. Please check the below image. This bug does not appear on old versions of the theme.

![image](https://user-images.githubusercontent.com/10679389/231445702-d7f38652-789d-4796-954a-205e3d89080f.png)

**Comment by TomiStyle** [comment]
I'm going to see if it solves

**Comment by michael-milette** [comment]
Hi @TomiStyle ,

Can you please confirm this issue? You should not see any characters in the password field, just dots.

Michael

**Comment by michael-milette** [comment]
As it has been almost 4 months since the last interaction in this conversation, I will assume that the issue has been resolved. Closing the issue. If this is still an issue, please feel free to re-open the ticket.

Best regards,

Michael Milette
