### ISSUE TITLE
Registration new user without CSS

### ISSUE THREAD

**Issue by alexjasoncrawl** [trema-tech/moodle-theme_trema#163]
If you have open the self registration in moodle, the theme will have no CSS for the age verification.

trema version: 4.1.0.0
moodle version: 4.1.2+ (Build: 20230418)
display res: 2560 width * 1440 height

![Screenshot 2023-04-22 at 16-59-14 Überprüfung von Alter und Aufenthaltsort](https://user-images.githubusercontent.com/131540640/233792076-b52d14ef-0d7e-4316-8032-b8fcf45c18c7.png)

**Comment by alexjasoncrawl** [comment]
...and the registration form has the wrong size (height to much) see picture.
![Screenshot 2023-04-22 at 17-04-54 Neues Nutzerkonto](https://user-images.githubusercontent.com/131540640/233792336-00e0eaff-57ce-425e-a643-793fd1cb0387.png)

**Comment by michael-milette** [comment]
Please test and integrate pull reuqest #178. Thanks! :-)

**Comment by michael-milette** [comment]
This issue is also mentioned in #143 . Please close both tickets when the pull request has been merged.

**Comment by rmady** [comment]
That's great! 
Thanks @michael-milette :)

Kind regards,
Rodrigo Mady
