### ISSUE TITLE
Wrong width on Admin Page

### ISSUE THREAD

**Issue by alexjasoncrawl** [trema-tech/moodle-theme_trema#165]
If you are on the Admin Page, the Scrollbar on bottom is showed up on a display res of 2560 px. There are wrong padding or margin on css, when right sidebar is showed. if the sidebar is closed, the horizontal scrollbar is not showing (the normal situation).

Tested on
trema: 4.1.0.0
moodle: 4.1.2+ (Build: 20230418)
display res: 2560 width * 1440 height
![Screenshot 2023-04-22 at 17-54-58 elearn Administration Suchen](https://user-images.githubusercontent.com/131540640/233794657-3fa76230-69e8-4a4f-9093-4a86ea318141.png)
![Screenshot 2023-04-22 at 17-54-43 elearn Administration Suchen](https://user-images.githubusercontent.com/131540640/233794658-116bc72f-8455-41b4-b2a3-0e2a46c95c8b.png)

**Comment by michael-milette** [comment]
Hi @alexjasoncrawl ,

I just tried it on Moodle 4.3 with the latest version of Trema here on GitHub which was last updated on September 8 at the exact same resolution as you indicated. Unfortunately, I have been unable to reproduce the issue. 

I understand that you are using Moodle 4.1 but could you please try it with the theme here on GitHub to see if that resolves the issue? Also, please try it with the Boost theme. The problem could be with Moodle core.

Best regards,

Michael Milette

**Comment by alexjasoncrawl** [comment]
Hey @michael-milette,

the Problem has been solved. Look like it was a Problem with the Boost theme.

Tested on 

Moodle 4.3+ (Build 20231110)
Trema 4.1.0.0 / 2023042100
