### ISSUE TITLE
Implement Copyright Year in Footer?

### ISSUE THREAD

**Issue by alexjasoncrawl** [trema-tech/moodle-theme_trema#166]
Hey guys

I love this theme so much. It's clean, simple, clear. However, I miss a theme option that shows the current copyright year in the footer section. I always have to enter them manually.

Is there a way to implement this with a theme option in the theme (maybe with PHP)?

I would have in mind something like:
© 1999 - current year (enter the start year manually)
© current year (only output the current year)

I would be happy about a solution.

Greetings
alexjasoncrawl

**Comment by michael-milette** [comment]
Hi @alexjasoncrawl ,

You can do this if you have the FilterCodes plugin installed.
https://moodle.org/plugins/filter_filtercodes

Once that is installed and activated, just add this to your footer:

© 1999 - {siteyear}
or
© {siteyear}

The plain-text tag {siteyear} will always be replaced by the current year... forever.

Hope you find this helpful.

Best regards,

Michael Milette
