### ISSUE TITLE
Message drawer does not follow color guideline

### ISSUE THREAD

**Issue by snack753** [trema-tech/moodle-theme_trema#169]
The message drawer appears in dark grey instead of following the colors defined in the theme settings. 
Other drawers, such as the drawer on the right, the notification popover, and the user action menu are well-designed. However, the message drawer does not fit the style guide.

**Comment by michael-milette** [comment]
In the next release of the Trema theme for Moodle LMS, the colours of the message drawer will be reset back to the Moodle default colours. Until then, please feel free to test the experimental "dev" branch.

Best regards,

Michael
