### ISSUE TITLE
HELP HELP HELP

### ISSUE THREAD

**Issue by lovingprojector1** [trema-tech/moodle-theme_trema#17]
I create Categories and Courses, but all the Trema theme ever shows is available courses, why make such a beautiful theme and take out literally one of the most useful tricks in the book. 
I need to be able to Categorize my courses and rooms. 
How do I get categories back? I need to know soon, or I'm going to have to go with a different Theme which sucks, because I really like this one.

**Comment by rmady** [comment]
Hi @lovingprojector1,

We need more info to help you.
Please, can you send your moodle and trema versions?
Some images of your Categories and Courses will be very helpful too.

**Comment by rmady** [comment]
I'm closing this issue 'cause we don't know how to replicate it.
Thanks a lot @lovingprojector1 

Best regards,
Rodrigo Mady

**Comment by lovingprojector1** [comment]
This was almost two years ago man. I've done solved my issues on my own
