### ISSUE TITLE
How to change font for the entire site

### ISSUE THREAD

**Issue by snack753** [trema-tech/moodle-theme_trema#170]
I would like to use a different font for the entire site.

Chose to go for openSans.

What we did is to add the following CSS code to the theme settings:
@font-face {
    font-family: "OpenSans";
    src: url([[font:theme|OpenSans-Regular.ttf]]) format("truetype");
}

This works pretty well with one exception: Buttons that use FA icons:
![image](https://github.com/trema-tech/moodle-theme_trema/assets/427666/1ef5f844-c356-4ffe-8d6b-09071784207e)

Here the classes fa and e.g. fa-download seem to override the global font definition for the entire <a> tag instead of just the icon part.

From my point of view the code needs to be changed to separate the .fa class from the button/<a> section to the icon only.
<img width="311" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/427666/4d23446c-b102-4bad-af89-9ffc070318f3">

Is there any workaround solve this?

**Comment by michael-milette** [comment]
The next major release of Trema will see the addition of 3 new theme settings to change the base font, the front page banner title, and the hx headings to any of the following font families below:

- Arial, Helvetica, sans-serif
- Verdana, Tahoma, sans-serif
- "Times New Roman", Times, serif
- Georgia, serif
- "Courier New", Courier, monospace
- Alegreya, serif
- "CrimsonText", serif
- "EBGaramond", sans-serif
- Lato, sans-serif
- Montserrat, sans-serif
- "NotoSans", sans-serif
- "OpenSans", sans-serif
- "PlayfairDisplay", serif
- Poppins, sans-serif
- Roboto, Arial, Helvetica, sans-serif

Feel free to try it out in the experimental "dev" branch.

Best regards,

Michael Milette
