### ISSUE TITLE
Text hard to see in various places due to default black background

### ISSUE THREAD

**Issue by farlo18** [trema-tech/moodle-theme_trema#171]
I've noticed when selecting to view another user's profile the "Add to Contacts" link is surrounded by a black background instead of it just being white like the rest of the site. This also occurs when on the home page and selecting to view messages. All the headings are black on a black background.

![users](https://github.com/trema-tech/moodle-theme_trema/assets/105552693/fefe7fc3-ed45-4c7a-abfc-7dc0fcba1ae7)
![messages](https://github.com/trema-tech/moodle-theme_trema/assets/105552693/0d576df6-de41-4867-890c-346113bb2d45)

**Comment by michael-milette** [comment]
This issue will be resolved in the next public release of the Trema theme for Moodle LMS. In the meantime, please feel free to test it out in the experimental "dev" branch.

Best regards,

Michael
