### ISSUE TITLE
Moodle 4.3: user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#173]
When I use Trema on Moodle 4.3, I get the following message on most pages including any site or course settings pages, My Courses and inside a course.

<img width="331" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/3808579/64a9a520-d9bb-441c-b5a5-c9cfd5b80e37">

Here is the text from the above screenshot:

**user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.**

- line 41 of \lib\ajax\ajaxlib.php: call to debugging()
- line 34 of \theme\trema\layout\drawers.php: call to user_preference_allow_ajax_update()
- line 1488 of \lib\outputrenderers.php: call to include()
- line 1414 of \lib\outputrenderers.php: call to core_renderer->render_page_layout()
- line 549 of \lib\outputrenderers.php: call to core_renderer->header()
- line 296 of \admin\renderer.php: call to plugin_renderer_base->__call()
- line 945 of \admin\index.php: call to core_admin_renderer->admin_notifications_page()

That message appears 3 times on each page.

I am installing the latest main branch available here on GitHub from September 8, 2023.

**Comment by rmady** [comment]
Hello @michael-milette,
You are awesome! Thanks lol

Kind regards,
Rodrigo Mady
