### ISSUE TITLE
Header colour change

### ISSUE THREAD

**Issue by sloanie1981** [trema-tech/moodle-theme_trema#18]
Hi guys,

Is it possible to change the theme header colour?It's currently white meaning that you can't see the 3 grey lines for the sidebar button. 

Thanks 
Stuart

**Comment by rmady** [comment]
Hi @sloanie1981,

We need more info to help you.
Please, can you send your moodle and trema versions?
Some images of header will be helpful too.

**Comment by sloanie1981** [comment]
Hi Rodrigo,

As I was detailing the version numbers, I noticed that I had version 3.7 of Moodle and 3.8 trema theme. I've updated Moodle and it's sorted the problem out now.

Thanks 
Stuart

**Comment by rmady** [comment]
Thanks a lot for the contrib @sloanie1981
