### ISSUE TITLE
Bug in footerbgcolor settings on dev branch

### ISSUE THREAD

**Issue by rmady** [trema-tech/moodle-theme_trema#182]
If you put footerbgcolor as primary, secondary, or background color the theme will not load some CSS.
Tested on dev branch and with the Moodle LMS on main branch with release '4.4dev+ (Build: 20240326)';
![image](https://github.com/trema-tech/moodle-theme_trema/assets/8494871/a0581f44-4f76-4577-83ce-2199ac667181)

**Comment by michael-milette** [comment]
This issue has been resolved. See the experimental dev branch for the updated code.
