### ISSUE TITLE
anchor

### ISSUE THREAD

**Issue by coffseducation** [trema-tech/moodle-theme_trema#183]
Hello!
At present the 'Learn more' button has an href anchor to cards.
I have turned off cards so the anchor goes nowhere.
I tried changing the anchor to Frontpage Body with a new id tag, but this does not work.
Is it possible to add anchors other than the default - or turn off the button?
Thanks.

**Comment by michael-milette** [comment]
Hi @coffseducation ,

It is not currently possible but will be within the next few weeks. We have been doing a lot of work on Trema these past few months including 125+ bug fixes, new features and enhancements, one of which is a setting to turn the button off in the cards.

Feel free to give the experimental dev branch a try and let us know what you think of the new Trema!

Best regards,

Michael Milette

**Comment by coffseducation** [comment]
Thanks Michael!

**Comment by michael-milette** [comment]
Hi @coffseducation ,

Just added a new option called "link" for the course cards Summary Type setting a few minutes ago. This will take you directly to the course, or the enrolment page if you are not already enrolled in the course. You still have the option to have no button of course.

Best regards,

Michael

**Comment by coffseducation** [comment]
> You still have the option to have no button of course.

How is this accomplished?
I have turned off 'Frontpage pages' but the button stiil appears - and of course links nowhere.

I would like to remove the 'Learn more' button or preferably have it anchor to Frontpage Body.
Thanks Michael!

**Comment by coffseducation** [comment]
I have now noticed the new addition of 'Default: #topofcontent'.
This solves my issue! 🙏
