### ISSUE TITLE
update Readme.MD required trema.tech expired domain?

### ISSUE THREAD

**Issue by rjfarnott** [trema-tech/moodle-theme_trema#184]
documentation seems to have some old links to irrelevant site in thai?

See the demo site
A demo site showing all available features of [Theme Trema](https://trema.tech/).

Documentation
Documentation is available in [Theme Trema](https://trema.tech/).

should be

See the demo site
A demo site showing all available features of [Theme Trema](https://github.com/trema-tech/moodle-theme_trema/blob/main/README.md).

Documentation
Documentation is available in [Theme Trema](https://401.rmady.com.br:8443/).

**Comment by michael-milette** [comment]
Hi @rjfarnott ,

Thank you for taking the time to send us your feedback. I agree, That documentation is quite outdated.

The good news is that there are lots of great changes coming for Trema soon including updates to the documentation. These will be published within the next few weeks. Feel free to review the documentation in the experimental dev branch in the meantime. If you find some issues, please feel free to create a new ticket.

Thanks again for the feedback. Your time and effort are very much appreciated.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
There is a new link for the demo site in the README.md file.
