### ISSUE TITLE
Mobile drawer not full screen height

### ISSUE THREAD

**Issue by PTSdeveloper007** [trema-tech/moodle-theme_trema#191]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

When Moodle on mobile view, the behavior of side menu isn't done right?  

### What do you think should have happened?

I expected '...'

### Steps to reproduce

1. Login as '...' (specify user role)
2. View site as mobile
3. Notice the behavior of side menu when clicked 

### Screenshots

<img width="377" alt="moodle_nav" src="https://github.com/trema-tech/moodle-theme_trema/assets/49137695/f31e66b8-17bc-4eac-a062-95a51081883e">

### Moodle version

Moodle 4.4.0

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @PTSdeveloper007 ,

Please provide additional details about what you think is not working as designed.

Best regards,

Michael Michael

**Comment by PTSdeveloper007** [comment]
Hi @michael-milette,

When on mobile view, I thought the side menu will cover the logo above and the X button only comes up after a few seconds. Please confirm if this is how its supposed to be

Regards, 

Peter

**Comment by michael-milette** [comment]
Ah! Thanks for the good suggestion. I will see what can be done about this and let you know when we have something for you to try out.

Michael

**Comment by michael-milette** [comment]
This issue has been resolved in the experimental dev branch. Please feel free to try it out if you can. This fix will be included in the next release of Trema.
