### ISSUE TITLE
Bug: contents not wrapped properly 

### ISSUE THREAD

**Issue by PTSdeveloper007** [trema-tech/moodle-theme_trema#193]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

contents within grade/reports not wrapped properly. Please see image attached

### What do you think should have happened?

I expected '...'

### Steps to reproduce

1. Login as '...' (specify user role)
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error or issue.
You get it?

### Screenshots

![image](https://github.com/trema-tech/moodle-theme_trema/assets/49137695/cab6904a-c410-4f65-b283-0400ce2e34b2)

### Moodle version

Moodle 4.4.0

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @PTSdeveloper007 ,

I would like to help you out. Please complete the following two questions:

**What do you think should have happened?**

I expected '...'

**Steps to reproduce**

Login as '...' (specify user role)
Go to '...'
Click on '....'
Scroll down to '....'
See error or issue.
You get it?

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
This issue has been resolved in the latest release of Trema 4.4.0.4.

Best regards,

Michael
