### ISSUE TITLE
Bug: buttons not aligned properly and dropdown icon not aligned properly

### ISSUE THREAD

**Issue by PTSdeveloper007** [trema-tech/moodle-theme_trema#196]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

buttons not aligned properly and dropdown icon not aligned properly

### What do you think should have happened?

buttons to be aligned properly and dropdown icon to be aligned properly

### Steps to reproduce

Please see image attached - all icons like this when on focus it reproduces this issue. Same for the top buttons as in image

### Screenshots

<img width="483" alt="buttonsPNG" src="https://github.com/trema-tech/moodle-theme_trema/assets/49137695/a1214b6c-4196-47de-a4dd-652ea83bd34e">

### Moodle version

Moodle 4.4.1

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @PTSdeveloper007 ,

Thank you for taking the time to report these issues. I tested and confirmed these on the Dashboard page, even on Moodle 4.3.

We will let you know as soon as they are fixed.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
This issue has been resolved in the experimental dev branch. Please feel free to try it out if you can. This fix will be included in the next release of Trema.
