### ISSUE TITLE
Bug: Text color of "Hidden from students" message

### ISSUE THREAD

**Issue by bernardo1975** [trema-tech/moodle-theme_trema#198]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

When hiding an activity/section inside a Moodle course, a notification "Hidden from students" on dark background appears -- the problem, however, is that the text is also dark (see Pic 1 of the screenshots below). Highlighting the text with the mouse makes the text visible (Pic 2).
Inspecting the html code, the issue is that "text-dark" is selected here (Pic 3). Changing this to "text-light" manually (Pic 4) has the expected and desired result, see Pic 5. 

### What do you think should have happened?

I expected the notification "Hidden from students" to look like Pic 5 (instead of like Pic 1).

### Steps to reproduce

Hide activity/section as lecturer/administrator.

### Screenshots

Pic 1:
![Screenshot_Hidden_1](https://github.com/user-attachments/assets/e3334b76-3671-4bd9-a11f-80aba2804f2e)

Pic 2:
![Screenshot_Hidden_2](https://github.com/user-attachments/assets/9ff14ce7-26a8-447a-904d-313d7ea4d978)

Pic 3:
![Screenshot_Hidden_3](https://github.com/user-attachments/assets/48866f37-e3d1-4081-8d5b-76b8d7e532c4)

Pic 4:
![Screenshot_Hidden_4](https://github.com/user-attachments/assets/dd51a7f4-9378-4ca2-bb9b-d1ff6aa0f495)

Pic 5:
![Screenshot_Hidden_5](https://github.com/user-attachments/assets/62dd8f52-82d1-4d5a-8256-361ac62a617f)

### Moodle version

Moodle 4.4.2 (Build: 20240812)

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### Workaround

No, unfortunately not.

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @bernardo1975 ,

I am having trouble reproducing the issue. It may be related to a particular colour combination. Are you using the latest version of Trema?

It would be helpful if you could please share your Trema colour settings with me including:

- **Primary color**
- **Secondary color**
- **Body background color**
- **Header Background color**
- **Drawer Background color**
- **Footer Background color**

If you can get these to me soon, I will try to include a fix for this in the upcoming update of Trema.

Best regards,

MIchael

**Comment by bernardo1975** [comment]
Hi Michael @michael-milette ,

sure, no problem. The version of Trema is 4.4.0.5 (2024071600).

Trema colour settings:
*    Primary color: #60C800
*    Secondary color: #8800AA
*    Body background color: #f1f1f1
*    Header Background color: White
*    Drawer Background color: Light
*    Footer Background color: Same as background color

Best & thank you.
Bernd

**Comment by bernardo1975** [comment]
I just updated to 4.4.0.6 (2024090500) with the same colour settings. It didn't resolve the problem.

**Comment by michael-milette** [comment]
Hi @bernardo1975 ,

Thank you for following up. I was able to successfully reproduce your issue. Please download and install release 4.4.0.7 which should solve the problem for you.

If you would be so kind, I would be thankful if you could let me know if this works for you too.

Best regards,

Michael Milette

**Comment by bernardo1975** [comment]
Great, thanks Michael @michael-milette , it worked:
![Screenshot_20240906_154028](https://github.com/user-attachments/assets/48e228c4-d7c0-407d-a44b-a682edaa4d94)
