### ISSUE TITLE
custommenuitems not working

### ISSUE THREAD

**Issue by seba11998** [trema-tech/moodle-theme_trema#20]
The option custommenuitems is not working as intended, When trying to create a dropdown menu, it only shows the first line.
![1](https://user-images.githubusercontent.com/14128134/77119193-b9f5b800-6a14-11ea-9772-41c2a9fff484.png)
![2](https://user-images.githubusercontent.com/14128134/77119198-bd893f00-6a14-11ea-8de9-c19e85985103.png)

**Comment by diegohemk** [comment]
Também estou com o mesmo problema. Ou, se possível, gostaria de saber como retirar o menu "Meus Cursos".

**Comment by trevorfurtado** [comment]
Thanks for reporting this problem, I didn't notice it. I believe that the recent commit using the Babel.js javascript compiler may be related, this problem did not affect the 3.5 version. I'll take a look soon, if you have any correction proposals feel free to make a pull request.

@diegohemk o menu "Meus cursos" é uma configuração do tema, você pode desabilitá-la em: Administração do site > Aparência > Temas > Trema > showmycourses

**Comment by tuxintrouble** [comment]
Hi I have fixed this after my last pull request. please see my repo.

**Comment by rmady** [comment]
Hi there,
Thanks a lot fot the contrib lol
