### ISSUE TITLE
Bug: Moodle 4.5 fix shape of Add New Picture button (looks like a slider)

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#200]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

In Moodle 4.5, there is what looks like a sliding switch. It is supposed to look like a button to add a picture.:

<img width="507" alt="image" src="https://github.com/user-attachments/assets/c0e9153b-b69e-4d34-9610-54c71b4faea1">

### What do you think should have happened?

I expected it to look like Edit Profile when using Boost

### Steps to reproduce

1. Log in as site admin.
2. Add a picture to your profile and save changes.
3. Edit profile again.

### Moodle version

Moodle 4.5 BETA dated 2024-09-27

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by rmady** [comment]
This fix is in the new version 4.5 of the theme Trema.
Please, check if everything is all right now.

--
Kind regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
Hi @rmady 

It looks like It is fixed everywhere. Thank you for fixing this!

Best regards,

Michael
