### ISSUE TITLE
Bug: Moodle 4.5 - Assignment Activity Submissions page too narrow

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#201]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Page is too narrow and does not wrap submissions.

### What do you think should have happened?

I expected the page to wrap submissions. In previous versions of Moodle, submissions had a horizontal scroll bar if it didn't fit in the page.

### Steps to reproduce

1. Log in as a **Site Administrator**.
2. Create a new course called **Test Assignment**.
3. Enrol yourself as a **Teacher** and a **Student**
4. Turn editing on.
5. Add an assignment activity.
6. Assignment name: **My Test Assignment**.
7. Submission type: Make sure **Online Text** is checked.
8. Click "**Save and Display**" button.
9. Click "**Add a submission**" button.
10. In the "**Online text**" field, just put the word "**test**".
11. Click "**Save changes**" button.
12. Click **Submissions** in the secondary menu.

### Screenshots

![image](https://github.com/user-attachments/assets/841e4563-5a48-4db0-a2aa-ed1914bebc78)

### Moodle version

Modole 4.5 BETA

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Web Browser: Chrome

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by rmady** [comment]
This fix is in the new version 4.5 of the theme Trema.
Please, check if everything is all right now.

--
Kind regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
Hi @rodrigo-mady ,

There still seem to be some display issues.

1. The first entry is cut off.

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/8e9f499e-57a6-4848-b00f-b91e96cf968a">

2. The page is not wide (compared to display in Boost)

<img width="1916" alt="image" src="https://github.com/user-attachments/assets/e88bcab7-dcee-4bf7-a50b-e6fc032f7070">

Best regards,

Michael

**Comment by michael-milette** [comment]
Page width has been significantly increased to show as much information as possible. On wider screens, it may show all the information. This was fixed at the same time as #204.
