### ISSUE TITLE
Bug: Arrow of usermenu dropdown is shown without showing the dropdown usermenu

### ISSUE THREAD

**Issue by JorineKoenderman** [trema-tech/moodle-theme_trema#202]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

We are running Trema version 4.4.0.7 (2024090700) with Moodle 4.4.3+ (Build: 20240920)

Below the user avatar you see the arrow that should only be attached and visible when you click to show the dropdown user menu.
The arrow is now always visible. It only disappears when you click on the avatar to show the dropdown user menu, do not select a menu item and click somewhere else on the page.

![image](https://github.com/user-attachments/assets/3832eb48-e16e-48d2-8f47-0ce2cbb8f1b6)

### What do you think should have happened?

I hope you can fix this and that the arrow will only show up when you are seeing the dropdown user menu

### Steps to reproduce

The arrow is visible on every page when you are logged into the website

### Moodle version

Moodle 4.4.3+ (Build: 20240920)

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### Workaround

No. Only option I see now is to completely make the arrow invisible by css like it is in standard boost theme.

### System information

I currently only tested it on desktop in google chrome on a windows laptop and on a computer with MacOS.
If more details are really necessary, please let me know.

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by rmady** [comment]
Hello @JorineKoenderman,

Thank you for your contribution lol
I made this fix but for now, it will be available just on the dev branch.
I'll make a new release next week.
Please, let me know if you find anything else and if you have time to test this fix.

Kind regards,
Rodrigo Mady

**Comment by JorineKoenderman** [comment]
Hello Rodrigo (@rmady),

Thank you for the quick fix. I just tested the code from the dev branch and I think it is working properly.
Thank you very much!

With kind regards,
Jorine

**Comment by michael-milette** [comment]
Hi @JorineKoenderman 

Thanks for letting us know that it works for you.

Best regards,

Michael Milette
