### ISSUE TITLE
Feature Request: Responsive Display Problem on Mobile Devices with Course Blocks

### ISSUE THREAD

**Issue by skandercci** [trema-tech/moodle-theme_trema#207]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [ ] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

I'm experiencing a responsive display issue with the Trema theme on Moodle. When accessing the homepage on mobile devices, the course blocks do not adjust properly to the screen size, appearing small and misaligned, as shown in the attached screenshot. The courses display correctly on desktop, but the responsive layout on mobile devices seems to be inconsistent.

Additionally, the size of the course blocks varies depending on the length of the course title, leading to an unbalanced look. This issue affects the overall usability and aesthetics on mobile.

Could you please investigate this responsive issue or suggest adjustments to improve the display on mobile devices?

Thank you!
![IMG_20241101_121931](https://github.com/user-attachments/assets/3190b250-066e-4f0a-a7e1-2f5f09c0c508)

### Screenshots / Mock-ups

![IMG_20241101_121915](https://github.com/user-attachments/assets/b3def8ed-0d13-4101-85f8-648d8857849f)

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by rmady** [comment]
Hello @skandercci,
Thank you for your contribution. I'll work on this fix and let you know as soon as I finish.
Please, let me know if you find anything else.

Kind regards,
Rodrigo Mady

**Comment by rmady** [comment]
Hi there @skandercci, 

I did the fix but for now, it is just on the dev branch. 
I'll add this fix to the release next week and let you know. 

Kind regards,
Rodrigo Mady

**Comment by rmady** [comment]
Hello @skandercci, 
The fix for this issue is available on moodle.org and in the main branch. 
Feel free to test and thank you very much for the contrib lol

Kind regards,
Rodrigo Mady
