### ISSUE TITLE
Feature Request: add toggle sensitive button in the login form

### ISSUE THREAD

**Issue by LucSta** [trema-tech/moodle-theme_trema#208]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [ ] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Since moodle 4.4, a new option is available to add an "eye" button near the password field in the login page. This feature is called "loginpasswordtoggle" in moodle. This feature lets the user see the password in plain text. It is very useful for beginner's users. Can you add it in the trema login form ?

### Screenshots / Mock-ups

![image](https://github.com/user-attachments/assets/1ad9a921-ab47-48b9-946a-ae7392605a2e)

### Planning on submitting a solution in a pull request (PR)?

No

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by rmady** [comment]
Hello @LucSta ,
Awesome! Thank you for your contribution. 
I'll work on this task and let you know as soon as I finish.
Please, let me know if you find anything else.

Kind regards,
Rodrigo Mady

**Comment by rmady** [comment]
Hi there @LucSta, 

I did the fix but for now, it is just on the dev branch. 
I'll add this fix to the release next week and let you know. 

Kind regards,
Rodrigo Mady

**Comment by rmady** [comment]
Hello @LucSta, 
The fix for this issue is available on moodle.org and in the main branch. 
Feel free to test and thank you very much for the contrib lol

Kind regards,
Rodrigo Mady

**Comment by LucSta** [comment]
Hello @Rmady,
Thank you very much for your work !
I will test the new version avalialble on moodle.org next week.
Thank you again !
Luc.

**Comment by LucSta** [comment]
Hello @rmady,
I tested the new version of trema this morning. The new feature works perfect ! Great job !
![login](https://github.com/user-attachments/assets/75cd4ea4-5f39-4d97-a89f-49778e64e3e4)
Thank you very much for your work,
Luc.
