### ISSUE TITLE
Buttons - Vertical align 

### ISSUE THREAD

**Issue by dimmuboy** [trema-tech/moodle-theme_trema#23]
Smaller buttons are wrong aligned because **line-height** is same for all height of buttons

![image](https://user-images.githubusercontent.com/12607479/80489893-cd276c00-8960-11ea-93fa-d5a126acc610.png)
.

**Comment by rmady** [comment]
Hi there lol
Thanks for the contrib.
Can you test for us @dimmuboy?

**Comment by dimmuboy** [comment]
Thanks,
it looks good now but small button is weirdly short. But I don't know if it's an issue or not.

![image](https://user-images.githubusercontent.com/12607479/82325904-481df880-99dc-11ea-92a1-995cb41ec26a.png)

**Comment by rmady** [comment]
Hi there @dimmuboy,
We think that it's okey this size for while.

Thanks a lot for the contrib lol
