### ISSUE TITLE
Missing strings in AMOS

### ISSUE THREAD

**Issue by dinism** [trema-tech/moodle-theme_trema#25]
I'm PT-PT translator.
In dropdown to select if you want to show the courses (general settings) the strings: don't show, show right and show left are harcoded to english. Can it be translated?
And in Style Guide tab?
Thanks

**Comment by rmady** [comment]
Hi there @dinism lol

Yes, can be and looks like that this is from Moodle Core.
Please, can you send us the image or link with this page? 

We can support the translations from all over the Moodle and plugins here: https://lang.moodle.org/
You can leanr more about translations in: https://docs.moodle.org/dev/Translating_plugins

Thanks a lot for the contrib.

**Comment by dinism** [comment]
Muito obrigado pela resposta.
..../admin/settings.php?section=themesettingtrema
![imagem](https://user-images.githubusercontent.com/14828021/85382765-324da700-b537-11ea-9460-ac850bd72e37.png)
