### ISSUE TITLE
3.9 Trema broke all the actions and menu dropdowns in moodle

### ISSUE THREAD

**Issue by nunoguerreiro** [trema-tech/moodle-theme_trema#26]
3.9 Trema broke all the actions and menu dropdowns in moodle

**Comment by rvkmar** [comment]
same problem. Unable to see logout and nav-bar hangs after a couple of clicks. Unable to select any system settings in 3.9

**Comment by rmady** [comment]
Hi guys,
I just fixed this in new release, can you test for us?
Thanks a lot for reporting this bug.

**Comment by nunoguerreiro** [comment]
tested - working now

**Comment by willianduran** [comment]
Muy bueno, probando ahora.

**Comment by dinism** [comment]
WORKING

**Comment by willianduran** [comment]
Working

**Comment by rvkmar** [comment]
Working

**Comment by hribeir0** [comment]
The language menu is not visible
Also, if select my courses menu on the right, it doesn't show. It's ok if it's on the left side.

Moodle 3.9 and Trema 3.9.0.1

**Comment by willianduran** [comment]
In the mode student if select my courses menu, it doesn't show. 
Moodle 3.9 and Trema 3.9.0.1

**Comment by wemakefuture** [comment]
Same issue, unable to edit courses, because button is missing. Please fix this its urgent. We cant edit courses anymore!

**Comment by rmady** [comment]
Hi guys, ok we'll see this as soon as possible :)

**Comment by hribeir0** [comment]
@wemakefuture No issue here. I've got the "Turn Editing On" button visible. Moodle 3.9 and Trema 3.9.0.1
