### ISSUE TITLE
Atto recorder (atto_recordrtc) not draggable

### ISSUE THREAD

**Issue by eslteacher** [trema-tech/moodle-theme_trema#27]
Moodle 3.9
I have a simple assignment and I want students to submit responses using the Atto audio recorder. 
When the audio recorder opens, the recorder has a ‘Move ’cursor on hover but the surrounding
lightbox seems fixed and prevents the recorder from being draggable. Tested on FF Chrome and edge latest. 

I can hide the lightbox in developer tools 
<div class="moodle-dialogue-base" aria-hidden="false"><div class="yui3-widget-mask moodle-dialogue-lightbox" style="position: fixed; width: 0%; height: 100%; top: 0px; left: 0px; z-index: 1042;">
Then I can drag the recorder to a new position.

Works fine in Boost 3.9

**Comment by eslteacher** [comment]
Fixed...
In /theme/trema/scss/trema/header.scss, remove 'z-index: 10000' on line 15 then purge all caches.
fixed by Gareth Barnard   gjbarnard@gmail.com

**Comment by gjb2048** [comment]
@eslteacher Should this be reopened so that the developers know its an issue to fix in the code they control?

**Comment by eslteacher** [comment]
Yep... You're exactly right!

**Comment by eslteacher** [comment]
Reopened so that Rodrigo and Trevor know its an issue to fix in the code they control.
Thanks, Gareth!

**Comment by michael-milette** [comment]
The suggested fix will be implemented in the next major release of the Trema theme. Feel free to check out the experimental dev branch in the meantime.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
The proposed fix will be implemented in the next major release of the Trema theme. Feel free to check out the experimental dev branch in the meantime.

Best regards,

Michael Milette
