### ISSUE TITLE
rtl does not work right

### ISSUE THREAD

**Issue by mjhoveida** [trema-tech/moodle-theme_trema#29]
The Frontpage banner does not work properly in rtl Language

**Comment by michael-milette** [comment]
Hi @mjhoveida ,

Could you please describe the problem you are experiencing? Also, please indicate the version of Trema and Moodle that you are using.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @mjhoveida  ,

Thank you for your patience. I tested this with the latest experimental dev branch (which should be published soon) and the problem has been resolved. I would be thankful it if you could give it a try and let me know how it goes for you.

Please note that this version of the Trema theme is only available for 4.0 to 4.4.

Best regards,

Michael Milette
