### ISSUE TITLE
Particles.js performance issue

### ISSUE THREAD

**Issue by rmady** [trema-tech/moodle-theme_trema#3]
Evaluate if the fork below brings performance improvements to particles.js
https://github.com/mmacheerpuppy/particles.js

**Comment by trevorfurtado** [comment]
CPU utilization was varying between 50%~70% in my environment, now it's between 30%~45%.

**Comment by trevorfurtado** [comment]
Thanks to @mmacheerpuppy for the improvement.
https://github.com/mmacheerpuppy/particles.js

**Comment by mmacheerpuppy** [comment]
Oh! You're welcome!  ❤️💛💚💙💜

**Comment by rmady** [comment]
Hey @trevorfurtado, I got things faster and better here too.
