### ISSUE TITLE
quiz actions are not appearing while doing the quiz.

### ISSUE THREAD

**Issue by nunoguerreiro** [trema-tech/moodle-theme_trema#30]
quiz navigation options are not appearing while doing the quiz. IF I disable the trema theme all is good....

![image](https://user-images.githubusercontent.com/1771943/97122017-19027480-173c-11eb-90fc-58cafc0ab06d.png)

**Comment by michael-milette** [comment]
I tested this on Moodle versions 3.10 and 3.11 using the latest version of Trema (master branch from GitHub) and the Quiz Navigation shows up in both.
![image](https://user-images.githubusercontent.com/3808579/147657460-04c5827c-07b3-478a-88bd-89204f9f6cc2.png)

However, it will appear near the bottom of the page if your browser window is less than 1200px wide. Try scrolling down.
![image](https://user-images.githubusercontent.com/3808579/147657608-a0f07f03-3b60-4ba9-8e82-61e7170b549c.png)

If this is still a problem, please indicate which version of Moodle you are using and we will re-open the ticket.

Best regards,

Michael
