### ISSUE TITLE
Advanced Grading Forms not working correctly 

### ISSUE THREAD

**Issue by dieweswolf** [trema-tech/moodle-theme_trema#31]
Please help with TREMA Theme for moodle

Hello there - I am struggling with the advanced grading forms and rubrics in the TREMA theme for moodle.
I am attaching these images:

https://photos.app.goo.gl/365WmBYUpfkQTcJeA

We had it working perfectly in the Klass theme - but it seems to glitch out and not work properly in TREMA. It seems to be some problem with the table and hidden fields?

I hope you can assist

Thank you

Wessie

**Comment by michael-milette** [comment]
Hi @dieweswolf ,

I am not familiar with that functionality. Could you please provide me with step-by-step instructions to reproduce the issue? We are in the process of a major upgrade of Trema and I would appreciate your help.

Also, please indicate the version of Trema and Moodle that you are using.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
As there has been no reply in over a month, I will close this ticket. Please feel free to re-submit a new ticket if the problem persists in the latest version of Trema.

Best regards,

Michael
