### ISSUE TITLE
Long activity link buttons are unreadable

### ISSUE THREAD

**Issue by techAdventurer** [trema-tech/moodle-theme_trema#36]
The activity link buttons are unreadable when the links are either too long, or the screen smaller.

See below the same page area, the first being the trema theme, the second being the Boost theme.

It seems the `white-space: no-wrap;` line is part of the problem, but I don't have time to investigate further at the moment.

![trema_theme](https://user-images.githubusercontent.com/45794420/118557312-4b6dd080-b765-11eb-82ec-0277b27713d2.png)

**Comment by rmady** [comment]
Hi there @techAdventurer 

I just draft a new release with this fixed, can you test for me? 

Thanks a lot for your help ;)

**Comment by techAdventurer** [comment]
Hi,

I just tested the new version and this problem is fixed!

Thanks for your work.
