### ISSUE TITLE
Emitir certificado no moodle

### ISSUE THREAD

**Issue by matosailla** [trema-tech/moodle-theme_trema#38]
Como configurar para que na finalização de um curso gerar um certificado?

**Comment by rmady** [comment]
Olá @matosailla,

Ai vai depender do seu ambiente, esta não é uma funcionalidade do tema.

Recomendo que dê uma olhada no custom certificate:
https://moodle.org/plugins/mod_customcert

E no certificado do Moodle HQ:
https://moodle.org/plugins/mod_certificate

**Comment by matosailla** [comment]
Eu devo colocar o plugin no servidor para funcionar?

**Comment by rmady** [comment]
Isso mesmo @matosailla.
Nos fóruns do Moodle tem diversas discussões a respeito, dê uma olhada ;)

https://moodle.org/mod/forum/discuss.php?d=68265

**Comment by matosailla** [comment]
Eu não sei nem por onde começar. Poderia me ajudar?

![AVA](https://user-images.githubusercontent.com/85761264/122276300-08fdf780-cebb-11eb-8467-f5611d9b65f6.png)

Esse é meu AVA 

![image](https://user-images.githubusercontent.com/85761264/122276470-3185f180-cebb-11eb-8b65-20bbd316b02d.png)

Essas são as opções que aparecem para mim na configuração do site.
