### ISSUE TITLE
Replace particles.js with tsParticles

### ISSUE THREAD

**Issue by matteoums** [trema-tech/moodle-theme_trema#39]
Hello,

Replacing the old particles.js with [tsParticles](https://github.com/matteobruni/tsparticles) could be a good improvement bringing a lot of new particles configurations that are not supported by particles.js (like particles emitters, motion reduction for motion sickness users, link triangles, fireworks, confetti)

**Comment by rmady** [comment]
Hi there @matteoums 

Thanks for your suggestion, I'll test it ASAP.

Actually I don't know if theme users are really using particles, 'cause almost all websites that I see just use an static image in login page.

**Comment by michael-milette** [comment]
Please note that Particles will be removed in the next major release of the Trema theme. I am therefore closing this ticket as it will no longer be relevant and there has been no further discussion since 2021.

Best regards,

Michael Milette
