### ISSUE TITLE
Add activity does not work in moodle 3.11

### ISSUE THREAD

**Issue by mjweb2009** [trema-tech/moodle-theme_trema#40]
I just update my moodle to moodle 3.11+ and add activity does not work in moodle 3.11.
can you fix it?

**Comment by rmady** [comment]
Hi there @mjweb2009,

Please, can you send some pictures? 
Did you see that you can disable the new style from topics in theme settings?

**Comment by mjweb2009** [comment]
![Captura](https://user-images.githubusercontent.com/29088541/122402036-69ee0400-cf7d-11eb-8ebe-99715770f91c.PNG)
Pressing the add activity button does nothing. Attached capture, with error in the browser console.
I've tried changing the trema style options in the settings, but I don't see any effect on the course.

**Comment by rmady** [comment]
Oh, I just get the problem now. 
Which course format are you using? Is it working in theme Boost? 

I'm trying to replicate the bug over here, thanks a lot.

**Comment by mjweb2009** [comment]
I am using the themes format, but it also fails with other formats.
I have seen that with the Boost theme it also fails.
I have updated the moodle from version 3.7 to 3.11

**Comment by mjweb2009** [comment]
Sorry, I just checked that it is an error derived from the update and it has nothing to do with the subject.
Thank you.
