### ISSUE TITLE
Emitir certificado no moodle

### ISSUE THREAD

**Issue by matosailla** [trema-tech/moodle-theme_trema#41]
Eu não sei nem por onde começar. Poderia me ajudar?

Esse é meu AVA:

![image](https://user-images.githubusercontent.com/85761264/122385213-e57e8f80-cf42-11eb-95d0-212034a89ed3.png)

Essas são as opções que aparecem para mim na configuração do site.

![image](https://user-images.githubusercontent.com/85761264/122385286-fcbd7d00-cf42-11eb-8252-8decdc87517b.png)

Agradeço desde já.

**Comment by rmady** [comment]
Bom dia @matosailla,

Fechei a tarefa anterior, pois esse espaço é apenas para discutirmos assuntos relacionados ao tema trema.
E inicialmente essa questão do certificado não tem ligação com esse plugin. 
Por favor, procurar os canais de comunicação corretos para tal. 

Pesquise no Google sobre como configurar um certificado no Moodle, temos diversos posts a respeito: https://moodle.org/mod/forum/discuss.php?d=68265
Temos um grupo no telegram onde a comunidade está sempre postando dúvidas também: https://t.me/moodlebrasil

Enfim, espero que dê tudo certo ;)
