### ISSUE TITLE
Error in admin panel

### ISSUE THREAD

**Issue by dbgerinfo** [trema-tech/moodle-theme_trema#43]
Just installed the theme for testing (very nice!) but I'm getting this error in admin dashboard (URL/my):

`Class 'core\check\environment\vendordir' not found`

Student dash works perfectly...

**Comment by rmady** [comment]
Hi there @dbgerinfo 

Please, can you send your Moodle version, build and trema versions?

**Comment by siteware-academy** [comment]
Hi!
Moodle 3.10+ (Build: 20201217)
Trema 3.11.0.1

I just notice that if I _disable_ `theme_trema | enableadmindashboard` the admin dash works again... weird...

**Comment by dbgerinfo** [comment]
Hi!

Moodle 3.10+ (Build: 20201217)
Trema 3.11.0.1

I just notice that if I _disable_ `theme_trema | enableadmindashboard` the admin dash works again... weird...

**Comment by michael-milette** [comment]
Hi @dbgerinfo ,

I tested using Moodle 3.10.7+ (Build: 20211022) and Trema 3.11.0.4 (the latest here on GitHub) but could not reproduce your issue. This could have been an issue with either an older version of Moodle or of Trema.

I have a few more questions for you to try and isolate the cause of the issue:

1. If you re-enable **enableadmindashboard**, does the issue come back again?
2. 1. Could you try it out with an updated version of Moodle and the Trema theme? 
3. How did you install Trema? Example: from GitHub, from a ZIP file downloaded from GitHub or from Moodle.org, from within Moodle via Moodle.org. 
4. Does any part of the **admindashboard** display at all when enabled? If so, please provide a screenshot.
5. If you temporarily set **Site Administration** > **Development** > **Debugging** to "DEVELOPER: extra Moodle debug messages for developers" and enable **Display debug messages**, is more of an error message displayed? If so, please provide the additional information.
6. Are you running Moodle in a containerized environment such as Docker, Kubernetes or OpenShift?
7. What is the operating system of your webserver? Example: Ubuntu, SUSE, CentOS, RedHat, Windows, MacOS.
8. If you navigate to **Site Administration** > **Server** > **Environment**, does the **Status** column for each row show a green **OK**?

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
It has been almost 2 years since the last question but there has been no response. I will assume that the issue has been resolved for currently supported versions of Moodle. I am therefore closing this ticket. If you are still experiencing the issue, please feel free to re-open the ticket.

Best regards,

Michael Milette
