### ISSUE TITLE
Error on login with PHP 8.0

### ISSUE THREAD

**Issue by dhigit** [trema-tech/moodle-theme_trema#44]
I am new on using Trema theme with latest version of Moodle (PHP8.0). Installation was OK, but after logout, I cannot login anymore with error message 'Exception - Attempt to modify property "particles" on null' at https://example.com/moodle/login/index.php. Please fix the bug, because I am using this for production and I cannot do anything.

Thanks

**Comment by dhigit** [comment]
Bug found at line 38. It was an issue related to reading resources with SSL.
I think you need to use curl instead of file_get_contents() to avoid SSL error while reading internal json file.

**Comment by jonasricardo** [comment]
também estou com o mesmo problema em meu ambiente de testes. Poderia verificar?

**Comment by michael-milette** [comment]
Moodle does not support PHP 8.0 yet (last checked on December 29, 2021).

_"[PHP 8.0 support](https://docs.moodle.org/dev/Moodle_and_PHP) is being implemented (see [MDL-70745](https://tracker.moodle.org/browse/MDL-70745) and not ready for production yet."_

For more information, see the [system requirements in the release notes for Moodle 3.11](https://docs.moodle.org/dev/Moodle_3.11_release_notes#Server_requirements)

As such, Trema does not support PHP 8.0 yet either. With that said, please try Trema 3.11.0.4 as it includes a fix to particles which **may** have addressed this issue.

**Comment by michael-milette** [comment]
Hi @dhigit and @jonasricardo,

Testing the latest version of Trema (Sept. 8, 2023) here on GitHub, I do not see any error when logging in using PHP 8.0 or 8.1. There are compatibiity issues in Moodle 4.3 which will hopefully be resolved soon however, none of them are PHP 8.2 related according to my testing so far.

For now, I will close this ticket. If this is still an issue for you using the latest version of the theme here on GitHub, please re-open this ticket and let us know which version of Moodle LMS and PHP you are using.

Best regards,

Michael Milette
