### ISSUE TITLE
theme doesn't work after plugin installation

### ISSUE THREAD

**Issue by luciamontefiori** [trema-tech/moodle-theme_trema#45]
Hi! 
I have installed a plugin this morning (E-voting), and after that the theme isn't working anymore. I tried uninstalling the plugin + uninstalling and installing back the theme + clear all caches
Nothing seems to work!

**Comment by luciamontefiori** [comment]
I have moodle version 3.8

**Comment by luciamontefiori** [comment]
update: it only works fine if I enable "theme designer mode"

**Comment by michael-milette** [comment]
Hello @luciamontefiori ,

Unfortunately, support for Moodle 3.8 ended in May 2021. I recommend you upgrade Moodle to at least 3.9 LTS (minimum), e-Voting to v3.9-r1 (2020070700), and Trema to the latest 3.11.0.4 or later.

Once you have updated all the software, should the problem persists, please answer the following questions and we will re-open this ticket:

1. What version of Moodle are you now running?
2. Also, when you say that the theme isn't working anymore, please describe what exactly happens?
3. If you temporarily set Site Administration > Development > Debugging to "DEVELOPER: extra Moodle debug messages for developers" and enable **Display debug messages**, is an error message displayed? If so, please provide the additional information.
4. Have you reported the issue to the developer of the E-Voting plugin? I suspect that they will also want you to update your software as Moodle 3.8 is no longer supported.
5. Does Trema stop working on all pages or just for E-Voting?

When I tested it on Moodle 3.11, it seems to work fine with Trema though it does have display issues (even in Boost!) which would need to be resolved by the developer of E-Voting.

Best regards,

Michael Milette
