### ISSUE TITLE
Login on the left instead on the center (SOLUTION INCLUDED)

### ISSUE THREAD

**Issue by x0341** [trema-tech/moodle-theme_trema#49]
can you share the code to make the login on the right or left of the screen instead on the center ?

**Comment by michael-milette** [comment]
Hi @rmady ,

I recommend making it on the left side for accessibility reasons. People using screen magnifiers might not find it if it is all the way to the right.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @nunoguerreiro ,

Try adding this in your theme settings:

    body#page-login-index #page.has-navbar #card-login {
        margin-top: 70px;
    }
    body#page-login-index #region-main{
        margin: 0;
        padding: 0;
        height: 100%;
        max-width: 720px;
        overflow-x: hidden;
        background-color: white!important;
    }
    body#page-login-index .container-fluid {
        padding-left: 0;
    }
    body#page-login-index #card-login {
        margin: 0;
    }
    #page-login-index .col-xl-6.col-sm-8 {
        min-width: 100%;
    }
    body#page-login-index div [role="main"] {
        overflow-x: hidden;
    }

I am making no promises! This was done quite quickly using the latest version of the theme and is not fully tested. It may not be compatible with future releases of Trema so your mileage may vary.

Please let me know how it works out for you.

Best regards,

Michael

**Comment by nunoguerreiro** [comment]
@michael-milette worked for now . thanks.

**Comment by michael-milette** [comment]
This seems to work for Trema 4.0.0.3:

    body#page-login-index #page.has-navbar #card-login {
        margin-top: 70px;
    }
    body#page-login-index .col-xl-6.col-sm-8 {
        min-width: 100%;
    }
    body#page-login-index #page-content {
        max-width: 720px;
        margin: 0;
        flex: 1 0 auto;
    }
    body#page-login-index #region-main-box {
        padding: 0;
        height: auto!important;
        max-height: 100%!important;
        background-color: white!important;
        overflow-x: hidden;
        margin: 0;
        padding: 0;
    }
    body#page-login-index div[role="main"] {
        overflow-x: hidden;
    }

Let me know if you have any questions or concerns.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
This feature will be included in the next major release of Trema. Feel free to try out the dev branch in the meantime.

Best regards,

Michael Milette
