### ISSUE TITLE
Error when Enable Admin Dashboard

### ISSUE THREAD

**Issue by nicolasguzca** [trema-tech/moodle-theme_trema#5]
Hi! First of all, thank you for this amazing theme!

I am getting 'Error reading from database' when I enable the Admin Dashboard. If I disable it it runs smoothly.

I am running Moodle 3.6.2 on Amazon Lightsail, with MySQL 5.7.23.

**Comment by trevorfurtado** [comment]
Hi @nicolasguzca, we detected this problem last week (9556584a5a7918325be56ae0db3b4cc508b5e214). It's occurring when you doesn't have any active course. We are finishing some others issues and hope release a new version in the next week. It will be of great help if you can get the last version directly here in github and test this issue before the release in moodle plugins. (use branch 'master' for M3.6 or 'MOODLE_35_STABLE' for M3.5)

**Comment by nicolasguzca** [comment]
Thank you! Will do

**Comment by trevorfurtado** [comment]
Fixed in 3.6.0.1
