### ISSUE TITLE
303 See Other redirection from front page

### ISSUE THREAD

**Issue by Chiew96** [trema-tech/moodle-theme_trema#6]
Hi, I have been using Trema for a while, and I found that when I am not logged in and visit the front page, the front page will be redirected to the login page.

This issue can be temporarily solved by visiting _Site administration > Front page settings_.

Trema version: 3.6.0.1
Moodle version: 3.6.2+ (build 20190118)

![DevTools - localhost_moodle_login_index php 13-Mar-19 3_41_34 PM](https://user-images.githubusercontent.com/48509733/54262639-a619a980-45a9-11e9-9171-3e55a67d1322.png)

**Comment by rmady** [comment]
Hi @Chiew96,

We don't undestand this issue, can you explain better? We try to simulate this issue in our enviroment and got no success.

Our demo website is working well with one initial page as you can see in the link: https://trema.tech

Is config 'forcelogin' enable?
What is the 'defaulthomepage' definition?
Is working well in boost or other themes?

Thanks for your contribution!

**Comment by Chiew96** [comment]
forcelogin: No
defaulthomepage: Dashboard
"Boost" and other themes do not have this issue.
This issue happens randomly.

The strange thing is that this issue has disappeared and has not happened in the past two week.

**Comment by rmady** [comment]
Hi there,

We are monitoring this issue and trying to replicate it but we don't get this yet.

So, thanks for the contribution and let us know if and when it happens again.
