### ISSUE TITLE
HTML5 Validation Error: You can't have a DIV inside a SPAN for Language menu

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#73]
Hi @rmady,

Error: Element div not allowed as child of element span in this context:

    <li class="nav-item lang-menu">
        <span class="dropdown nav-item">
            <a class="nav-link" id="drop-down-6180326819b09618032674b85c15" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#" title="Language" aria-label="Display language menu">
                <i area-hidden="true" class="fa fa-globe"></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="drop-down-6180326819b09618032674b85c15">
                <a class="dropdown-item" href="https://localhost/admin/settings.php?section=themesettings&amp;lang=en" lang="en">English</a>
                <a class="dropdown-item" href="https://localhost/admin/settings.php?section=themesettings&amp;lang=fr_ca" lang="fr-ca">Français</a>
            </div>
        </span>
    </li>

In addition:

- The dropdown menu does not provide any indication of the current language.
- The first item in the dropdown list is not automatically selected as it is with custom menu items.
- The language cannot be switched on the Login page. This is not only an accessibility issue but a problem for sites where the login page is forced.

Let me know if you have any questions or concerns.

Best regards,

Michael

**Comment by rmady** [comment]
Great @michael-milette, this change was awesome.
I'm learning a lot with your commits ;)

--
Best regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
Thanks @rmady 👍 You are very kind.

Thank you for integrating the changes.

Best regards,

Michael
