### ISSUE TITLE
Site name heading on login page should be H1, not H2

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#75]
Hi @rmady ,

The name of the site on the login page is an H2. There is no H1 on the page. This is an accessibility issue.

I suggest that the H2 should actually be an H1 with a class of H2 to preserve the size as it is in Boost.

Let me know if you have any questions or concerns.

Best regards,

Michael

**Comment by rmady** [comment]
Thanks @michael-milette, this change was great.

Best regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
You are very welcome @rmady 👍 

Thank you for integrating the changes.

Best regards,

Michael
