### ISSUE TITLE
Please add a .gitignore file to the theme

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#77]
It would be really nice if there was a good .gitignore file included with the theme files to ignore accidental inclusion of editor files, temporary files, composer files, etc.

**Comment by rmady** [comment]
Thanks @michael-milette for the super gitignore.

Best regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
You are very welcome @rmady 👍 

Thank you for accepting this pull request.

Best regards,

Michael
