### ISSUE TITLE
grade assignment page top text is missing

### ISSUE THREAD

**Issue by sestrauss** [trema-tech/moodle-theme_trema#8]
Thank you for your excellent theme. It looks great, but I notice that the top of the user information is cut off on the grade assignment page. This does not happen in Boost. See attached screen shots.
Thanks for looking into this.

![2019-04-01_15-04-53](https://user-images.githubusercontent.com/5521034/55353275-e5446780-5490-11e9-8259-dcbb1501eeaa.gif)
![2019-04-01_14-57-16](https://user-images.githubusercontent.com/5521034/55353284-eecdcf80-5490-11e9-9db1-6d0fc532ef5c.gif)

**Comment by rmady** [comment]
Hi there @sestrauss,

We fixed this issue just adding overflow auto to this page in commit 9f1203eed0133e517176d9e7590df9652416bb5e. 
Can you test this for us?

We saw a lot of minors adjustments for this page and for grade table, so we created the issue #10 for improve the layout of mod_assign. Feel free to comment and sugest adjusts for the mod_assign.

Thanks for your contribution!

**Comment by sestrauss** [comment]
Thanks for your quick reply!

I tried installing the moodle-theme_trema-feature_courselistpopup branch--and also adding 

   body.path-mod-assign.pagelayout-embedded {
       overflow: auto;
   } 

to module.scss. That did not seem to make a difference. However, I suspect I did something wrong in my testing.

**Comment by trevorfurtado** [comment]
Hi @sestrauss ,
This issue was harder to fix than we expected but I think we came to a solution.
Please, update your trema with our new 3.x.0.2 release and give us your feedback if possible.
Thanks for your contribution!

**Comment by sestrauss** [comment]
That works. Thanks!
