### ISSUE TITLE
Blanking Frontpage banner / carousel button text should also remove button / link

### ISSUE THREAD

**Issue by joelanthonywalczak** [trema-tech/moodle-theme_trema#83]
How do I get rid of the learn more button on the site home page?

**Comment by michael-milette** [comment]
Hi @joelanthonywalczak 

Unfortunately removing the Learn More text from the Trema settings still leaves the button. It would be good to fix this in a future release of the theme. For now, add some CSS in the theme settings. Something like the following should do it:

    #frontpage-banner-content a {display:none!important}

For more information on using CSS, see:
https://www.codecademy.com/learn/learn-css

Best regards,

Michael

**Comment by michael-milette** [comment]
If you remove the link, the button will not try to display.

**Comment by rmady** [comment]
Excelent contrib @michael-milette and @joelanthonywalczak 

I put in the new release today.
Thanks a lot to make Trema better lol

Kind regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
Thank you!
