### ISSUE TITLE
Front Page has no H1

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#86]
I have a very simple front page with just a title and a button in the single banner. When I check the source code, I noticed that the title in the banner is an H2 and there is no H1 in the page. This is an accessibility issue.

**Comment by rmady** [comment]
Great feature @michael-milette 

Thanks a lot lol

Kind regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
Thank you!
