### ISSUE TITLE
Error when any carousel banner field settings are empty

### ISSUE THREAD

**Issue by michael-milette** [trema-tech/moodle-theme_trema#92]
Creating a banner without an image, title, subtitle, button text, button link and button class will display errors on home page when viewed with debugging set to developer mode.

**Comment by rmady** [comment]
Hello @michael-milette,
Thank you for this contrib, I saw that these errors were happening but didn't know how to solve. 
Thanks a lot for helping Trema to become better.

Kind regards,
Rodrigo Mady

**Comment by michael-milette** [comment]
No problem @rmandy! Thank you too.
